Bash: Fixed indents

diff --git a/bin/flac2mp3 b/bin/flac2mp3
--- a/bin/flac2mp3
+++ b/bin/flac2mp3
@@ -16,26 +16,27 @@
 
 # check dependencies
 function deps {
-    DEPENDENCIES="flac lame"
+  DEPENDENCIES="flac lame"
 
-    deps_ok=YES
-    for dep in $DEPENDENCIES
-    do
-        if ! which $dep &>/dev/null;  then
-            printf "This script requires \033[1;31m$dep\033[0m to run but it is not installed\n\n"
-            deps_ok=NO
-        fi
-    done
+  deps_ok=YES
 
-    if [[ "$deps_ok" == "NO" ]]; then
-        printf "Unmet dependencies ^\n"
-        printf "Aborting!\n"
-        # failure 
-        exit 1
-    else
-        # success
-        return 0
+  for dep in $DEPENDENCIES
+  do
+    if ! which $dep &>/dev/null; then
+      printf "This script requires \033[1;31m$dep\033[0m to run but it is not installed\n\n"
+      deps_ok=NO
     fi
+  done
+
+  if [[ "$deps_ok" == "NO" ]]; then
+    printf "Unmet dependencies ^\n"
+    printf "Aborting!\n"
+    # failure 
+    exit 1
+  else
+    # success
+    return 0
+  fi
 }
 
 # check dependencies
@@ -43,20 +44,21 @@ deps
 
 # conversion
 for a in *.flac; do
-    # give output correct extension
-    OUTF="${a[@]/%flac/mp3}"
+  # give output correct extension
+  OUTF="${a[@]/%flac/mp3}"
 
-    # get the tags
-    ARTIST=$(metaflac "$a" --show-tag=ARTIST | sed s/.*=//g)
-    TITLE=$(metaflac "$a" --show-tag=TITLE | sed s/.*=//g)
-    ALBUM=$(metaflac "$a" --show-tag=ALBUM | sed s/.*=//g)
-    GENRE=$(metaflac "$a" --show-tag=GENRE | sed s/.*=//g)
-    TRACKNUMBER=$(metaflac "$a" --show-tag=TRACKNUMBER | sed s/.*=//g)
-    DATE=$(metaflac "$a" --show-tag=DATE | sed s/.*=//g)
+  # get the tags
+  ARTIST=$(metaflac "$a" --show-tag=ARTIST | sed s/.*=//g)
+  TITLE=$(metaflac "$a" --show-tag=TITLE | sed s/.*=//g)
+  ALBUM=$(metaflac "$a" --show-tag=ALBUM | sed s/.*=//g)
+  GENRE=$(metaflac "$a" --show-tag=GENRE | sed s/.*=//g)
+  TRACKNUMBER=$(metaflac "$a" --show-tag=TRACKNUMBER | sed s/.*=//g)
+  DATE=$(metaflac "$a" --show-tag=DATE | sed s/.*=//g)
 
-    # stream flac into the lame encoder
-    flac -c -d "$a" | lame -V0 --add-id3v2 --pad-id3v2 --ignore-tag-errors \
-        --ta "$ARTIST" --tt "$TITLE" --tl "$ALBUM"  --tg "${GENRE:-12}" \
-        --tn "${TRACKNUMBER:-0}" --ty "$DATE" - "$OUTF"
+  # stream flac into the lame encoder
+  flac -c -d "$a" | lame -V0 --add-id3v2 --pad-id3v2 --ignore-tag-errors \
+    --ta "$ARTIST" --tt "$TITLE" --tl "$ALBUM"  --tg "${GENRE:-12}" \
+    --tn "${TRACKNUMBER:-0}" --ty "$DATE" - "$OUTF"
 done
 
+# vim:ft=sh:ts=8:sw=2:sts=2:tw=78:fenc=utf-8:et
