Setting up OSDISTRO variable for zsh environment

diff --git a/.config/zsh/lib/defuns/zenv b/.config/zsh/lib/defuns/zenv
--- a/.config/zsh/lib/defuns/zenv
+++ b/.config/zsh/lib/defuns/zenv
@@ -9,13 +9,16 @@
 # OSSHORT     Contains the short name of the operating system, e.g.
 #             Linux, OSX, etc.  Will be used in zsh scripts to
 #             provide OS-wide configuration.
-#
+# OSDISTRO    Contains the distribution-name in case of a Linux
+#             system, e.g. Debian, Gentoo, Ubuntu, Fedora, OpenSuSE.
 
 # function zenv {
 
 # If one of these is already set we won't override it.
 # Thus we need a copy before we load the cache.
-[ -z "$OSSHORT" ] || OSSHORT_BACK="$OSSHORT"
+[ -z "$OSLONG" ]   || OSLONG_BACK="$OSLONG"
+[ -z "$OSSHORT" ]  || OSSHORT_BACK="$OSSHORT"
+[ -z "$OSDISTRO" ] || OSDISTRO_BACK="$OSDISTRO"
 
 if [ -z "$ZSH_CACHE_DIR" ]; then
   ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
@@ -23,7 +26,7 @@ fi
 
 # Probable it is no so good, to silently create a directory, but I
 # use it on my Linux and macOS machines.  Thus, this will create this
-# directory if is not present.
+# directory if isn't present.
 [ -d $ZSH_CACHE_DIR ] || mkdir -p $ZSH_CACHE_DIR
 
 # If the values of the somewhat more complex variables are already
@@ -44,42 +47,76 @@ ZSH_ENV_CACHE_LOCK=$ZSH_ENV_CACHE.lock
 if [ -r $ZSH_ENV_CACHE ]; then
   source $ZSH_ENV_CACHE
 
-  [ x$OSLONG_BACK = x ]  || OSLONG=$OSLONG_BACK
-  [ x$OSSHORT_BACK = x ] || OSSHORT=$OSSHORT_BACK
+  # Restore previously set variables (if any).
+  [ x$OSLONG_BACK = x ]   || OSLONG=$OSLONG_BACK
+  [ x$OSSHORT_BACK = x ]  || OSSHORT=$OSSHORT_BACK
+  [ x$OSDISTRO_BACK = x ] || OSDISTRO=$OSDISTRO_BACK
 
-  # Stop sourcing this file
+  # Stop sourcing this file and exit with a success status.
   return 0
 fi
 
 # If we can't load from cache, then set all the required variables
 # by hand.
 
+# Create the cache directory if it isn't present.  Again.
 [ -d ${ZSH_ENV_CACHE%/*} ] || mkdir -p ${ZSH_ENV_CACHE%/*}
 
-OSLONG=$(uname)
+# A workaround to get OS name on Linux and macOS systems.
+OSLONG="$(uname -o 2>/dev/null || uname -s)"
 
 case $OSLONG in
-  Linux)
-    OSLONG=GNU/Linux
+  *Linux)
     OSSHORT=Linux
+    if builtin which lsb_release >/dev/null ; then
+      OSDISTRO=$(lsb_release -i | cut -f2-)
+    elif [ -f /etc/redhat-release ]; then
+      OSDISTRO=$(head -n 1 /etc/redhat-release | cut -d' ' -f1)
+    elif [ -f /etc/os-release ]; then
+      awk -F= '/^ID/{ printf "%s", $2; exit }' /etc/os-release
+    elif [ -f /etc/arch-release ]; then
+      OSDISTRO=Arch
+    elif builtin which pacman >/dev/null; then
+      OSDISTRO=Arch
+    elif [ -f /etc/issue ]; then
+      OSDISTRO=$(head -n 1 /etc/issue | cut -d' ' -f1)
+    else
+      OSDISTRO=Unknown
+    fi
+    ;;
+  FreeBSD)
+    OSSHORT=$OSLONG
     ;;
   Darwin)
     OSLONG=macOS
     OSSHORT=OSX
     ;;
+  *)
+    OSSHORT=Unknown
 esac
 
 if ! touch $ZSH_ENV_CACHE >/dev/null 2>&1; then
-  (>&2 printf "zenv: unable to create file %s\\n" $ZSH_ENV_CACHE)
+  (>&2 printf "Unable to create cache file: \"%s\"\\n" $ZSH_ENV_CACHE)
 else
   chmod 600 $ZSH_ENV_CACHE
+
+  echo "export OSLONG=\"$OSLONG\"" >> $ZSH_ENV_CACHE
+  echo "export OSSHORT=\"$OSSHORT\"" >> $ZSH_ENV_CACHE
+
+  if [ $OSSHORT = Linux ]; then
+    echo "export OSDISTRO=\"$OSDISTRO\"" >> $ZSH_ENV_CACHE
+  fi
 fi
 
-echo "export OSLONG=\"$OSLONG\"" >> $ZSH_ENV_CACHE
-echo "export OSSHORT=\"$OSSHORT\"" >> $ZSH_ENV_CACHE
-
 export OSLONG OSSHORT
-echo Yay!
+
+if [ $OSSHORT = Linux ]; then
+  export OSDISTRO
+fi
+
+# We don't need lock file now.
+rm -f $ZSH_ENV_CACHE_LOCK
+
 # }
 
 # Local Variables:
