Add a workaround for macOS to not overwrite PATHs

diff --git a/.config/zsh/conf.d/paths b/.config/zsh/conf.d/paths
--- a/.config/zsh/conf.d/paths
+++ b/.config/zsh/conf.d/paths
@@ -54,3 +54,27 @@ fi
 }
 
 export PATH
+
+# ~/.zshenv is supposed to be the ideal place to set the PATH.
+# However on OS X and Arch (and previously Gentoo), the system
+# /etc/zprofile which is executed after ~/.zshenv will overwrite
+# the PATH variable - so to workaround that issue, PATH settings
+# should be re-read in ~/.zprofile
+if [ ! -d ${XDG_CACHE_HOME:-$HOME/.cache}/zsh ]; then
+  mkdir -p ${XDG_CACHE_HOME:-$HOME/.cache}/zsh
+fi
+
+if command -v hostname >/dev/null 2>&1; then
+  ZSH_PATH_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/$(hostname -s).paths"
+else
+  ZSH_PATH_CACHE=${XDG_CACHE_HOME:-$HOME/.cache}/zsh/localhost.paths
+fi
+
+if touch $ZSH_PATH_CACHE >/dev/null 2>&1; then
+  chmod 600 $ZSH_PATH_CACHE
+  cat <<EOF > $ZSH_PATH_CACHE
+export PATH="$PATH"
+EOF
+else
+  >&2 echo -n "zenv: Unable to create PATH cache file: \"$ZSH_PATH_CACHE\""
+fi
