Cleaned up duplicated and old stuff

diff --git a/.config/zsh/conf.d/rbenv b/.config/zsh/conf.d/rbenv
--- a/.config/zsh/conf.d/rbenv
+++ b/.config/zsh/conf.d/rbenv
@@ -4,11 +4,11 @@
 #   .zshenv -> .zprofile -> .zshrc -> [rbenv] -> .zlogin
 
 if (( ! ${+RBENV_SHELL} )); then
-    if (( ${+commands[rbenv]} )); then
-        eval "$(rbenv init -)"
-    else
-        >&2 echo "command rbenv not found"
-    fi
+  if (( ${+commands[rbenv]} )); then
+    eval "$(rbenv init -)"
+  else
+    >&2 echo "command rbenv not found"
+  fi
 fi
 
 # Local Variables:
