Amend rust configuration

diff --git a/.config/zsh/conf.d/rust b/.config/zsh/conf.d/rust
--- a/.config/zsh/conf.d/rust
+++ b/.config/zsh/conf.d/rust
@@ -3,8 +3,23 @@
 # This file is sourced on interactive invocations of zsh.
 #   .zshenv -> .zprofile -> .zshrc -> [rust] -> .zlogin
 
-if [ -f $HOME/.cargo/env ]; then
-  source $HOME/.cargo/env
+if [ -d $HOME/.cargo/bin ]; then
+    path=($HOME/.cargo/bin $path)
+fi
+
+if (( ! ${+RUST_SRC_PATH} )); then
+  if (( ${+commands[rustc]} )); then
+    # Fetch the Rust sourcecode as documented here
+    # https://github.com/racer-rust/racer#configuration
+    RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/library
+    if [ -d $RUST_SRC_PATH ]; then
+      export RUST_SRC_PATH
+    else
+      unset RUST_SRC_PATH
+    fi
+  else
+    >&2 echo "command rustc not found"
+  fi
 fi
 
 # Local Variables:
